# Apply DEA models

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime

import src.pyoDEA as pyoDEA

In [2]:
x = [
    [41.00, 25.00, 15.00, 45.00, 18.00, 52.00, 32.00, 55.00],
]
y = [
    [51.04, 43.19, 13.50, 71.89, 36.76, 78.67, 65.34, 98.90],
]
q = [
    [51.04, 40.55, 13.50, 75.00, 31.36, 76.34, 47.47, 74.38],
]

In [3]:
pyoDEA.efficiency_inputs_report(x, y, goals = [], is_VRS = False, is_tradeoff = False)

Input 1  Efficiency Input  Resources saving of Input 1
0     41.0          0.609570                 1.600762e+01
1     25.0          0.845941                 3.851469e+00
2     15.0          0.440696                 8.389554e+00
3     45.0          0.782263                 9.798150e+00
4     18.0          1.000000                 3.552714e-15
5     52.0          0.740803                 1.347824e+01
6     32.0          0.999830                 5.440696e-03
7     55.0          0.880503                 6.572361e+00

In [4]:
pyoDEA.efficiency_inputs_report(x, y, goals = q, is_VRS = False, is_tradeoff = False)

Input 1  Efficiency Input  Resources saving of Input 1
0     41.0          0.609570                    16.007617
1     25.0          0.794233                     5.144178
2     15.0          0.440696                     8.389554
3     45.0          0.816104                     8.275299
4     18.0          0.853101                     2.644178
5     52.0          0.718862                    14.619151
6     32.0          0.726384                     8.755713
7     55.0          0.662202                    18.578890

In [5]:
pyoDEA.DEA(x, y, goals = q, is_input_oriented = True, is_VRS = False, is_tradeoff_model = True)

{'phi': array([0.48765625, 0.63538629, 0.35255713, 0.88835691, 0.68248096,
        0.86263497, 0.58110718, 0.7946424 ]),
 'du': {(0, 0): 0.0,
  (0, 1): 0.0,
  (0, 2): 0.0,
  (0, 3): 6.639999999999992,
  (0, 4): 0.0,
  (0, 5): 15.268000000000004,
  (0, 6): 0.0,
  (0, 7): 14.876000000000003},
 'dl': {(0, 0): 10.208,
  (0, 1): 8.11,
  (0, 2): 2.7,
  (0, 3): 0.0,
  (0, 4): 6.272,
  (0, 5): 0.0,
  (0, 6): 9.494,
  (0, 7): 0.0}}

In [6]:
x = [
    [41.00, 25.00, 15.00, 45.00, 18.00, 52.00, 32.00, 55.00],
]

y = [
    [0.99, 0.79507143, 0.77319939, 0.75986585, 0.71560186, 0.71559945, 0.70580836, 0.78661761]
]

q = [
    [0.99, 0.98521429, 0.91959818, 0.87959755, 0.74680559,0.74679836, 0.71742508, 0.95985284]
]

In [7]:
pyoDEA.DEA(x, y, is_VRS = False)

array([0.4684369 , 0.61697263, 1.        , 0.32758512, 0.77125628,
       0.26697243, 0.42789437, 0.27746022])

In [8]:
pyoDEA.DEA(x, y, q, is_input_oriented = True, is_VRS = False)

array([0.4684369 , 0.76452281, 1.18934157, 0.37920255, 0.80488681,
       0.27861197, 0.43493698, 0.33856474])

In [9]:
pyoDEA.DEA(x, y, q, is_input_oriented = True, is_VRS = True)

array([1.        , 1.61704278, 2.17046674, 0.61688647, 0.83333333,
       0.28846154, 0.46875   , 0.67971956])